# Generated by Django 6.0.6 on 2026-07-01 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('icon', models.CharField(blank=True, help_text='Contoh: fas fa-code, fas fa-paint-brush', max_length=50, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Thumbnail')),
                ('level', models.CharField(choices=[('beginner', 'Pemula'), ('intermediate', 'Menengah'), ('advanced', 'Lanjutan')], default='beginner', max_length=20, verbose_name='Level')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Dipublikasi'), ('archived', 'Diarsipkan')], default='draft', max_length=20, verbose_name='Status')),
                ('total_duration', models.IntegerField(default=0, verbose_name='Total Durasi (menit)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Kategori')),
                ('instructor', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Instruktur')),
            ],
            options={
                'verbose_name': 'Kursus',
                'verbose_name_plural': 'Kursus',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Module')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Kursus')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Module',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Materi')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('text', 'Teks'), ('article', 'Artikel'), ('quiz', 'Kuis')], default='text', max_length=20, verbose_name='Tipe Konten')),
                ('content', models.TextField(blank=True, verbose_name='Konten')),
                ('video_url', models.URLField(blank=True, verbose_name='URL Video')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durasi (menit)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Bisa Di-preview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Kosongkan jika tidak ada batas waktu', null=True, verbose_name='Batas Waktu (menit)')),
                ('passing_grade', models.PositiveIntegerField(blank=True, help_text='Kosongkan jika tidak ada syarat kelulusan', null=True, verbose_name='Nilai Minimum (%)')),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='Kosongkan jika tidak terbatas', null=True, verbose_name='Maks Percobaan')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='Acak Urutan Soal')),
                ('shuffle_choices', models.BooleanField(default=False, verbose_name='Acak Urutan Pilihan Jawaban')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Materi',
                'verbose_name_plural': 'Materi',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'order')},
            },
        ),
    ]
