# Generated by Django 6.0.6 on 2026-07-01 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Teks Soal')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Pilihan Ganda'), ('true_false', 'Benar/Salah')], default='multiple_choice', max_length=20, verbose_name='Tipe Soal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('explanation', models.TextField(blank=True, help_text='Akan ditampilkan setelah user menjawab', verbose_name='Penjelasan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(limit_choices_to={'content_type': 'quiz'}, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.lesson', verbose_name='Materi Kuis')),
            ],
            options={
                'verbose_name': 'Soal',
                'verbose_name_plural': 'Soal',
                'ordering': ['lesson', 'order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500, verbose_name='Teks Pilihan')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Jawaban Benar')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question', verbose_name='Soal')),
            ],
            options={
                'verbose_name': 'Pilihan Jawaban',
                'verbose_name_plural': 'Pilihan Jawaban',
                'ordering': ['question', 'order'],
                'unique_together': {('question', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Skor (%)')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total Soal')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Jawaban Benar')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Waktu Dihabiskan (detik)')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Lulus')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Mulai')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.lesson', verbose_name='Materi Kuis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Percobaan Kuis',
                'verbose_name_plural': 'Percobaan Kuis',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Jawaban Benar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt', verbose_name='Percobaan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizzes.question', verbose_name='Soal')),
                ('selected_choice', models.ForeignKey(blank=True, help_text='Kosongkan jika tidak dijawab', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.choice', verbose_name='Jawaban Dipilih')),
            ],
            options={
                'verbose_name': 'Jawaban User',
                'verbose_name_plural': 'Jawaban User',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
